In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load the Netflix dataset from the CSV file
df = pd.read_csv("netflix_titles.csv")
print(df)

     show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]

In [11]:
# first 5 rows
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
# Last 5 rows
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [12]:
# Random 5 Rows
print(df.sample(5))

     show_id     type                                   title  \
7802   s7803    Movie                            Pulp Fiction
5921   s5922    Movie  Bill Burr: I'm Sorry You Feel That Way
3256   s3257    Movie              Iliza Shlesinger: Unveiled
311     s312  TV Show                               Control Z
4693   s4694    Movie                                 Pad Man

               director                                               cast  \
7802  Quentin Tarantino  John Travolta, Samuel L. Jackson, Uma Thurman,...
5921          Jay Karas                                          Bill Burr
3256        Steve Paley                                   Iliza Shlesinger
311                 NaN  Ana Valeria Becerril, Michael Ronda, Yankel St...
4693           R. Balki  Akshay Kumar, Sonam Kapoor, Radhika Apte, Jyot...

            country         date_added  release_year rating   duration  \
7802  United States    January 1, 2019          1994      R    154 min
5921  United States   December 5, 2014          2014  TV-MA     81 min
3256  United States  November 19, 2019          2019  TV-MA     78 min
311          Mexico     August 4, 2021          2021  TV-MA  2 Seasons
4693          India    August 21, 2018          2018  PG-13    130 min

                                              listed_in  \
7802                Classic Movies, Cult Movies, Dramas
5921                                    Stand-Up Comedy
3256                                    Stand-Up Comedy
311   International TV Shows, Spanish-Language TV Sh...
4693      Dramas, International Movies, Romantic Movies

                                            description
7802  This stylized crime caper weaves together stor...
5921  Bill Burr escapes the zombie apocalypse, explo...
3256  Here comes the bride, and she's got plenty to ...
311   When a hacker begins releasing students' secre...
4693  Despite public humiliation and resistance, an ...

In [5]:
# shape
print(df.shape)

(8807, 12)

In [6]:
# columns names
print(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [7]:
# information
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 3.9 MB
None

In [8]:
# describe
print(df.describe())

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [13]:
# Total cells
print(df.size)

105684

In [9]:
# missing values
print(df.isnull().sum())

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [14]:
# Total Missing Values
print(df.isnull().sum().sum())

4307

In [10]:
# Duplicate values
print("Duplicate_values:- ",df.duplicated().sum())

Duplicate_values:-  0

In [15]:
# create copy
df_copy = df.copy()

In [16]:
# Fill missing values
df_copy["director"] = df_copy["director"].fillna("unknown")
df_copy["cast"] = df_copy["cast"].fillna("unknown")
df_copy["country"] = df_copy["cast"].fillna("unknown")
df_copy["rating"] = df_copy["cast"].fillna("unknown")
df_copy["date_added"] = df_copy["date_added"].fillna("unknown")
df_copy["duration"] = df_copy["duration"].fillna("unknown")

In [17]:
# Check missing values again
print(df_copy.isnull().sum())

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [18]:
# select single column
print(df["title"])

0        Dick Johnson Is Dead
1               Blood & Water
2                   Ganglands
3       Jailbirds New Orleans
4                Kota Factory
                ...
8802                   Zodiac
8803              Zombie Dumb
8804               Zombieland
8805                     Zoom
8806                   Zubaan
Name: title, Length: 8807, dtype: str

In [19]:
df.keys()

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [20]:
# Select multiple column
print(df[["title","type","country","release_year"]])

                      title     type        country  release_year
0      Dick Johnson Is Dead    Movie  United States          2020
1             Blood & Water  TV Show   South Africa          2021
2                 Ganglands  TV Show            NaN          2021
3     Jailbirds New Orleans  TV Show            NaN          2021
4              Kota Factory  TV Show          India          2021
...                     ...      ...            ...           ...
8802                 Zodiac    Movie  United States          2007
8803            Zombie Dumb  TV Show            NaN          2018
8804             Zombieland    Movie  United States          2009
8805                   Zoom    Movie  United States          2006
8806                 Zubaan    Movie          India          2015

[8807 rows x 4 columns]

In [21]:
# First row
print(df.iloc[0])

show_id                                                        s1
type                                                        Movie
title                                        Dick Johnson Is Dead
director                                          Kirsten Johnson
cast                                                          NaN
country                                             United States
date_added                                     September 25, 2021
release_year                                                 2020
rating                                                      PG-13
duration                                                   90 min
listed_in                                           Documentaries
description     As her father nears the end of his life, filmm...
Name: 0, dtype: object

In [22]:
# First 5 rows and first 3 column
print(df.iloc[0:5,0:3])

  show_id     type                  title
0      s1    Movie   Dick Johnson Is Dead
1      s2  TV Show          Blood & Water
2      s3  TV Show              Ganglands
3      s4  TV Show  Jailbirds New Orleans
4      s5  TV Show           Kota Factory

In [23]:
# Only movies
movies = df[df["type"] == "Movie"]
print(movies)

     show_id   type                             title  \
0         s1  Movie              Dick Johnson Is Dead
6         s7  Movie  My Little Pony: A New Generation
7         s8  Movie                           Sankofa
9        s10  Movie                      The Starling
12       s13  Movie                      Je Suis Karl
...      ...    ...                               ...
8801   s8802  Movie                           Zinzana
8802   s8803  Movie                            Zodiac
8804   s8805  Movie                        Zombieland
8805   s8806  Movie                              Zoom
8806   s8807  Movie                            Zubaan

                           director  \
0                   Kirsten Johnson
6     Robert Cullen, José Luis Ucha
7                      Haile Gerima
9                    Theodore Melfi
12              Christian Schwochow
...                             ...
8801                Majid Al Ansari
8802                  David Fincher
8804                Ruben Fleischer
8805                   Peter Hewitt
8806                    Mozez Singh

                                                   cast  \
0                                                   NaN
6     Vanessa Hudgens, Kimiko Glenn, James Marsden, ...
7     Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...
9     Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...
12    Luna Wedler, Jannis Niewöhner, Milan Peschel, ...
...                                                 ...
8801  Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...

                                                country          date_added  \
0                                         United States  September 25, 2021
6                                                   NaN  September 24, 2021
7     United States, Ghana, Burkina Faso, United Kin...  September 24, 2021
9                                         United States  September 24, 2021
12                              Germany, Czech Republic  September 23, 2021
...                                                 ...                 ...
8801                       United Arab Emirates, Jordan       March 9, 2016
8802                                      United States   November 20, 2019
8804                                      United States    November 1, 2019
8805                                      United States    January 11, 2020
8806                                              India       March 2, 2019

      release_year rating duration  \
0             2020  PG-13   90 min
6             2021     PG   91 min
7             1993  TV-MA  125 min
9             2021  PG-13  104 min
12            2021  TV-MA  127 min
...            ...    ...      ...
8801          2015  TV-MA   96 min
8802          2007      R  158 min
8804          2009      R   88 min
8805          2006     PG   88 min
8806          2015  TV-14  111 min

                                             listed_in  \
0                                        Documentaries
6                             Children & Family Movies
7     Dramas, Independent Movies, International Movies
9                                     Comedies, Dramas
12                        Dramas, International Movies
...                                                ...
8801           Dramas, International Movies, Thrillers
8802                    Cult Movies, Dramas, Thrillers
8804                           Comedies, Horror Movies
8805                Children & Family Movies, Comedies
8806    Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
6     Equestria's divided. But a bright-eyed hero be...
7     On a photo shoot in Ghana, an American model s...
9     A woman adjusting to life after a loss contend...
12    After most of her family is murdered in a terr...
...                                                 ...
8801  Recovering alcoholic Talal wakes up inside a s...
8802  A political cartoonist, a crime reporter and a...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[6131 rows x 12 columns]

In [25]:
# content released after 2020
recent_content = df[df["release_year"] > 2020]
print(recent_content[["title","type","release_year"]])

                          title     type  release_year
1                 Blood & Water  TV Show          2021
2                     Ganglands  TV Show          2021
3         Jailbirds New Orleans  TV Show          2021
4                  Kota Factory  TV Show          2021
5                 Midnight Mass  TV Show          2021
...                         ...      ...           ...
1468  What Happened to Mr. Cha?    Movie          2021
1551                      Hilda  TV Show          2021
1696               Polly Pocket  TV Show          2021
2920              Love Is Blind  TV Show          2021
8437     The Netflix Afterparty  TV Show          2021

[592 rows x 3 columns]

In [27]:
# movies released between 2015 and 2020
result = df[
    (df["type"] == "Movie") &
    (df["release_year"] >= 2015) &
    (df["release_year"] <= 2020)
]
print(result[["title","release_year"]])

                                                  title  release_year
0                                  Dick Johnson Is Dead          2020
16    Europe's Most Dangerous Man: Otto Skorzeny in ...          2020
38                                  Birth of the Dragon          2017
73                                         King of Boys          2018
78                                       Tughlaq Durbar          2020
...                                                 ...           ...
8787                          You Can’t Fight Christmas          2017
8788                                       You Carry Me          2015
8794                                             اشتباك          2016
8801                                            Zinzana          2015
8806                                             Zubaan          2015

[3740 rows x 2 columns]

In [28]:
# content with a specific rating
result = df[df["rating"] == "TV-MA"]
print(result[["title","type","rating"]])

                       title     type rating
1              Blood & Water  TV Show  TV-MA
2                  Ganglands  TV Show  TV-MA
3      Jailbirds New Orleans  TV Show  TV-MA
4               Kota Factory  TV Show  TV-MA
5              Midnight Mass  TV Show  TV-MA
...                      ...      ...    ...
8762         Wrong Side Raju    Movie  TV-MA
8769  Y.M.I.: Yeh Mera India    Movie  TV-MA
8788            You Carry Me    Movie  TV-MA
8798                Zed Plus    Movie  TV-MA
8801                 Zinzana    Movie  TV-MA

[3207 rows x 3 columns]

In [33]:
# content released in 2021 and 2022
result = df[
    (df["release_year"] == 2021) |
    (df["release_year"] == 2019)
]
print(df[["title","release_year"]])

                      title  release_year
0      Dick Johnson Is Dead          2020
1             Blood & Water          2021
2                 Ganglands          2021
3     Jailbirds New Orleans          2021
4              Kota Factory          2021
...                     ...           ...
8802                 Zodiac          2007
8803            Zombie Dumb          2018
8804             Zombieland          2009
8805                   Zoom          2006
8806                 Zubaan          2015

[8807 rows x 2 columns]

In [32]:
# Latest release year
print(df["release_year"].max())

2021

In [34]:
# Earliest release year
print(df["release_year"].min())

1925

In [35]:
# Average release year
print(df["release_year"].mean())

2014.1801975701146

In [37]:
# count content by type
print(df["type"].value_counts())

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [38]:
# count content by rating
print(df["rating"].value_counts())

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [40]:
# Top 10 countries by number of records
print(df["country"].value_counts().head(10))

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [41]:
# movies and TV shows count
print(df.groupby("type")["show_id"].count())

type
Movie      6131
TV Show    2676
Name: show_id, dtype: int64

In [43]:
# Year wise content count
print(df.groupby("release_year").count())

              show_id  type  title  director  cast  country  date_added  \
release_year
1925                1     1      1         0     0        0           1
1942                2     2      2         2     1        2           2
1943                3     3      3         3     0        3           3
1944                3     3      3         3     1        3           3
1945                4     4      4         3     1        4           4
...               ...   ...    ...       ...   ...      ...         ...
2017             1032  1032   1032       773   912      966        1032
2018             1147  1147   1147       760  1026     1038        1146
2019             1030  1030   1030       629   917      913        1030
2020              953   953    953       548   827      852         953
2021              592   592    592       297   494      383         592

              rating  duration  listed_in  description
release_year
1925               1         1          1            1
1942               2         2          2            2
1943               3         3          3            3
1944               3         3          3            3
1945               4         4          4            4
...              ...       ...        ...          ...
2017            1031      1031       1032         1032
2018            1147      1147       1147         1147
2019            1030      1030       1030         1030
2020             953       953        953          953
2021             592       592        592          592

[74 rows x 11 columns]

In [46]:
# type wise release year statistics
print(df.groupby("type")["release_year"].agg(["min","max","mean","count"]))

          min   max         mean  count
type
Movie    1942  2021  2013.121514   6131
TV Show  1925  2021  2016.605755   2676

In [47]:
# Top 10 years with most content
year_count = df["release_year"].value_counts().head(10)
print(year_count)

release_year
2018    1147
2017    1032
2019    1030
2020     953
2016     902
2021     592
2015     560
2014     352
2013     288
2012     237
Name: count, dtype: int64

# ***Sorting***

In [48]:
# sort by release year ascending
print(df.sort_values("release_year"))

     show_id     type                               title  \
4250   s4251  TV Show   Pioneers: First Women Filmmakers*
7790   s7791    Movie                      Prelude to War
8205   s8206    Movie                The Battle of Midway
8739   s8740    Movie  Why We Fight: The Battle of Russia
8763   s8764    Movie     WWII: Report from the Aleutians
...      ...      ...                                 ...
3         s4  TV Show               Jailbirds New Orleans
2         s3  TV Show                           Ganglands
18       s19    Movie                           Intrusion
1         s2  TV Show                       Blood & Water
68       s69    Movie                          Schumacher

                                               director  \
4250                                                NaN
7790                                        Frank Capra
8205                                          John Ford
8739                        Frank Capra, Anatole Litvak
8763                                        John Huston
...                                                 ...
3                                                   NaN
2                                       Julien Leclercq
18                                           Adam Salky
1                                                   NaN
68    Hanns-Bruno Kammertöns, Vanessa Nöcker, Michae...

                                                   cast        country  \
4250                                                NaN            NaN
7790                                                NaN  United States
8205                          Henry Fonda, Jane Darwell  United States
8739                                                NaN  United States
8763                                                NaN  United States
...                                                 ...            ...
3                                                   NaN            NaN
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
18    Freida Pinto, Logan Marshall-Green, Robert Joh...            NaN
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
68                                   Michael Schumacher            NaN

              date_added  release_year rating   duration  \
4250   December 30, 2018          1925  TV-14   1 Season
7790      March 31, 2017          1942  TV-14     52 min
8205      March 31, 2017          1942  TV-14     18 min
8739      March 31, 2017          1943  TV-PG     82 min
8763      March 31, 2017          1943  TV-PG     45 min
...                  ...           ...    ...        ...
3     September 24, 2021          2021  TV-MA   1 Season
2     September 24, 2021          2021  TV-MA   1 Season
18    September 22, 2021          2021  TV-14     94 min
1     September 24, 2021          2021  TV-MA  2 Seasons
68    September 15, 2021          2021  TV-14    113 min

                                              listed_in  \
4250                                           TV Shows
7790                      Classic Movies, Documentaries
8205                      Classic Movies, Documentaries
8739                                      Documentaries
8763                                      Documentaries
...                                                 ...
3                                Docuseries, Reality TV
2     Crime TV Shows, International TV Shows, TV Act...
18                                            Thrillers
1       International TV Shows, TV Dramas, TV Mysteries
68    Documentaries, International Movies, Sports Mo...

                                            description
4250  This collection restores films from women who ...
7790  Frank Capra's documentary chronicles the rise ...
8205  Director John Ford captures combat footage of ...
8739  This installment of Frank Capra's acclaimed do...
8763  Filmmaker John Huston narrates this Oscar-nomi...
...                                                 ...
3     Feuds, flirtations and toilet talk go down amo...
2     To protect his family from a powerful drug lor...
18    After a deadly home invasion at a couple’s new...
1     After crossing paths at a party, a Cape Town t...
68    Through exclusive interviews and archival foot...

[8807 rows x 12 columns]

In [49]:
# descending
print(df.sort_values("release_year" , ascending=False))

     show_id     type                                          title  \
1         s2  TV Show                                  Blood & Water
2         s3  TV Show                                      Ganglands
3         s4  TV Show                          Jailbirds New Orleans
31       s32  TV Show                             Chicago Party Aunt
30       s31    Movie                                Ankahi Kahaniya
...      ...      ...                                            ...
8739   s8740    Movie             Why We Fight: The Battle of Russia
8660   s8661    Movie  Undercover: How to Operate Behind Enemy Lines
7790   s7791    Movie                                 Prelude to War
8205   s8206    Movie                           The Battle of Midway
4250   s4251  TV Show              Pioneers: First Women Filmmakers*

                                               director  \
1                                                   NaN
2                                       Julien Leclercq
3                                                   NaN
31                                                  NaN
30    Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket C...
...                                                 ...
8739                        Frank Capra, Anatole Litvak
8660                                          John Ford
7790                                        Frank Capra
8205                                          John Ford
4250                                                NaN

                                                   cast        country  \
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
31    Lauren Ash, Rory O'Malley, RuPaul Charles, Jil...            NaN
30    Abhishek Banerjee, Rinku Rajguru, Delzad Hiwal...            NaN
...                                                 ...            ...
8739                                                NaN  United States
8660                                                NaN  United States
7790                                                NaN  United States
8205                          Henry Fonda, Jane Darwell  United States
4250                                                NaN            NaN

              date_added  release_year rating   duration  \
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
31    September 17, 2021          2021  TV-MA   1 Season
30    September 17, 2021          2021  TV-14    111 min
...                  ...           ...    ...        ...
8739      March 31, 2017          1943  TV-PG     82 min
8660      March 31, 2017          1943  TV-PG     61 min
7790      March 31, 2017          1942  TV-14     52 min
8205      March 31, 2017          1942  TV-14     18 min
4250   December 30, 2018          1925  TV-14   1 Season

                                              listed_in  \
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
31                                          TV Comedies
30     Dramas, Independent Movies, International Movies
...                                                 ...
8739                                      Documentaries
8660                      Classic Movies, Documentaries
7790                      Classic Movies, Documentaries
8205                      Classic Movies, Documentaries
4250                                           TV Shows

                                            description
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
31    Chicago Party Aunt Diane is an idolized troubl...
30    As big city life buzzes around them, lonely so...
...                                                 ...
8739  This installment of Frank Capra's acclaimed do...
8660  This World War II-era training film dramatizes...
7790  Frank Capra's documentary chronicles the rise ...
8205  Director John Ford captures combat footage of ...
4250  This collection restores films from women who ...

[8807 rows x 12 columns]

In [50]:
# sort titles alphabettically
print(df.sort_values("title"))

     show_id     type                          title  \
2036   s2037    Movie                         #Alive
2304   s2305    Movie  #AnneFrank - Parallel Stories
2481   s2482    Movie              #FriendButMarried
2324   s2325    Movie            #FriendButMarried 2
5973   s5974    Movie                          #Roxy
...      ...      ...                            ...
6177   s6178  TV Show                       忍者ハットリくん
4914   s4915  TV Show                           海的儿子
7101   s7102  TV Show                           마녀사냥
5022   s5023    Movie                        반드시 잡는다
7108   s7109    Movie            최강전사 미니특공대 : 영웅의 탄생

                         director  \
2036                       Cho Il
2304  Sabina Fedeli, Anna Migotto
2481                Rako Prijanto
2324                Rako Prijanto
5973              Michael Kennedy
...                           ...
6177                          NaN
4914                          NaN
7101                          NaN
5022                Hong-seon Kim
7108                Young Jun Lee

                                                   cast      country  \
2036                           Yoo Ah-in, Park Shin-hye  South Korea
2304                        Helen Mirren, Gengher Gatti        Italy
2481  Adipati Dolken, Vanesha Prescilla, Rendi Jhon,...    Indonesia
2324  Adipati Dolken, Mawar de Jongh, Sari Nila, Von...    Indonesia
5973  Jake Short, Sarah Fisher, Booboo Stewart, Dann...       Canada
...                                                 ...          ...
6177                                                NaN        Japan
4914  Li Nanxing, Christopher Lee, Jesseca Liu, Appl...          NaN
7101  Si-kyung Sung, Se-yoon Yoo, Dong-yup Shin, Ji-...  South Korea
5022                                      Baek Yoon-sik  South Korea
7108  Um Sang-hyun, Yang Jeong-hwa, Jeon Tae-yeol, S...          NaN

              date_added  release_year rating   duration  \
2036   September 8, 2020          2020  TV-MA     99 min
2304        July 1, 2020          2019  TV-14     95 min
2481        May 21, 2020          2018   TV-G    102 min
2324       June 28, 2020          2020   TV-G    104 min
5973      April 10, 2019          2018  TV-14    105 min
...                  ...           ...    ...        ...
6177   December 23, 2018          2012  TV-Y7  2 Seasons
4914      April 27, 2018          2016  TV-14   1 Season
7101   February 19, 2018          2015  TV-MA   1 Season
5022   February 28, 2018          2017  TV-MA    110 min
7108   September 1, 2018          2018  TV-Y7     68 min

                                              listed_in  \
2036     Horror Movies, International Movies, Thrillers
2304                Documentaries, International Movies
2481      Dramas, International Movies, Romantic Movies
2324      Dramas, International Movies, Romantic Movies
5973                          Comedies, Romantic Movies
...                                                 ...
6177                             Anime Series, Kids' TV
4914                  International TV Shows, TV Dramas
7101  International TV Shows, Korean TV Shows, Stand...
5022            Dramas, International Movies, Thrillers
7108                           Children & Family Movies

                                            description
2036  As a grisly virus rampages a city, a lone man ...
2304  Through her diary, Anne Frank's story is retol...
2481  Pining for his high school crush for years, a ...
2324  As Ayu and Ditto finally transition from best ...
5973  A teenage hacker with a huge nose helps a cool...
...                                                 ...
6177  Hailing from the mountains of Iga, Kanzo Hatto...
4914  Two brothers start a new life in Singapore, wh...
7101  Four Korean celebrity men and guest stars of b...
5022  After people in his town start turning up dead...
7108  Miniforce, a special task force of elite range...

[8807 rows x 12 columns]

# ***Numpy Operation's***

In [51]:
# Convert release year into NumPy array
years = df["release_year"].to_numpy()
print(years)

[2020 2021 2021 ... 2009 2006 2015]

In [52]:
# Maximum release year
print(np.max(years))

2021

In [53]:
# Minimum release year
print(np.min(years))

1925

In [54]:
# Average release year
print(np.mean(years))

2014.1801975701146

In [55]:
# Median release year
print(np.median(years))

2017.0

In [56]:
# Count releases after 2020
print(np.sum(years > 2020))

592

In [57]:
# Create release period using NumPy
period = np.where(years >= 2020, "Recent", "Before 2020")
print(period)

['Recent' 'Recent' 'Recent' ... 'Before 2020' 'Before 2020' 'Before 2020']

In [58]:
# Add new column using NumPy result
df["release_period"] = period
print(df[["title", "release_year", "release_period"]].head())

                   title  release_year release_period
0   Dick Johnson Is Dead          2020         Recent
1          Blood & Water          2021         Recent
2              Ganglands          2021         Recent
3  Jailbirds New Orleans          2021         Recent
4           Kota Factory          2021         Recent

In [59]:
# Convert date_added into datetime
df["date_added"] = pd.to_datetime(
    df["date_added"],
    errors="coerce"
)
print(df["date_added"].head())

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[us]

In [60]:
# Extract year when content was added to Netflix
df["date_added_year"] = df["date_added"].dt.year
print(df[["title", "date_added", "date_added_year"]].head())

                   title date_added  date_added_year
0   Dick Johnson Is Dead 2021-09-25           2021.0
1          Blood & Water 2021-09-24           2021.0
2              Ganglands 2021-09-24           2021.0
3  Jailbirds New Orleans 2021-09-24           2021.0
4           Kota Factory 2021-09-24           2021.0

In [61]:
# Extract numeric duration
df["duration_value"] = pd.to_numeric(
    df["duration"].str.extract(r"(\d+)")[0],
    errors="coerce"
)
print(df[["title", "type", "duration", "duration_value"]].head())

                   title     type   duration  duration_value
0   Dick Johnson Is Dead    Movie     90 min            90.0
1          Blood & Water  TV Show  2 Seasons             2.0
2              Ganglands  TV Show   1 Season             1.0
3  Jailbirds New Orleans  TV Show   1 Season             1.0
4           Kota Factory  TV Show  2 Seasons             2.0